package enums;

public enum Enemies {
    TARANTULA,
    ABIGCLUMPOFSPIDERS,
    DADDYLONGLEGS,
    BANANASPIDER,
    ORYX,
    KELLOGG,
    AREALLYBIGBEETLE,
    TERROR,
    YOUROWNREFLECTION,
    KHUSHI,
    SEAGULLTRYINGTOEATYOURSANDWICH,
    PIRATE,
    SLOWWIFI,
    KRUEGER,
    EDWARDSCISSORHANDS

}
